# Generated by Django 4.2.6 on 2023-10-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_from', models.CharField(max_length=100)),
                ('location', models.FilePathField(path='/var/vmail/gist.email')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailserver.account')),
                ('smtp_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailserver.virtualuser')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=100)),
                ('gist', models.TextField(max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gists', to='mailserver.account')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gist', to='processor.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_to', models.EmailField(max_length=254)),
                ('location', models.FilePathField(path='/var/vmail/gist.email/gist_report/Maildir/Sent')),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mailserver.account')),
                ('emails', models.ManyToManyField(related_name='reports', to='processor.email')),
                ('gists', models.ManyToManyField(related_name='reports', to='processor.emailgist')),
            ],
        ),
    ]
