# Generated by Django 4.2.6 on 2023-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_emailgist_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgist',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailgistreport',
            name='location',
            field=models.FilePathField(path='/var/vmail/gist.email'),
        ),
    ]
