# Generated by Django 4.2.6 on 2023-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_emailgist_complete_alter_emailgistreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='location',
            field=models.FilePathField(max_length=1000, path='/var/vmail/gist.email'),
        ),
    ]
