# Generated by Django 4.2.6 on 2023-10-31 15:25

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Email = apps.get_model("processor", "Email")
    EmailGist = apps.get_model("processor", "EmailGist")
    EmailGistReport = apps.get_model("processor", "EmailGistReport")
    for row in Email.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    for row in EmailGist.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    for row in EmailGistReport.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):
    dependencies = [
        ("processor", "0005_add_uuids"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]