# Generated by Django 4.2.7 on 2023-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_remove_null_on_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgistreport',
            name='subject',
            field=models.CharField(blank=True, default='GIST Report', max_length=100),
        ),
    ]
