# Generated by Django 4.2.7 on 2023-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0008_emailgistreport_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgist',
            name='priority',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
