# Generated by Django 4.2.6 on 2023-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='report_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
