# Generated by Django 4.2.6 on 2023-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('mailserver', '0002_account_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='report_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='account',
            name='report_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='report_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
